### PR TITLE
Completes export import feature

### PR DESCRIPTION
**Pull request by abeade**
Updates dependencies
Adds tests for import/export feature
Updates README

refs: #8

### CODE REVIEW

**Comment by abeade** [comment]
Hi @kensiprell I did the missing taks for this feature.
I saw your comment https://github.com/kensiprell/browser-websocket-client/pull/8#issuecomment-554757786 about stop mantaining the plugin.
As I wish to publish this feature, can you transfer me the plugin?
Thanks!

**Comment by kensiprell** [comment]
Albert,

I tried to transfer the repo just now, but I received this error:

abeade/browser-websocket-client already exists

I assume you have to delete your fork first.

I have to research again how to transfer the Chrome extension. Do you have a Chrome developer account?

Ken

**Comment by abeade** [comment]
Hi Ken,

I think you should merge this PR fist because is pointing to my fork (not sure if needed but just in case). As soon as you merged it, I will delete my fork and you should be able to transfer the repo.

About the extension, yes I have webstore developer account. To do the transfer I guess you should use this form https://support.google.com/chrome_webstore/contact/dev_account_transfer

**Comment by abeade** [comment]
@kensiprell I've deleted my fork. Thanks.

**Pull request merged**
